### ISSUE TITLE
pagination shows when there's only one page

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events#11]
The pager shows even when there's only one page of results -- I have it (via the Drupal module) [on the Biotech dev site](https://dev-biotech.pantheonsite.io/events), but I can't be sure I'll still have it like that when you have a chance to look, so I'll include a link to the demo tool with an example of the "bug" in the first comment on this issue.

**Comment by alisonjo315** [comment]
[Example of the bug on the super awesome events embed demo tool!](https://cu-communityapps.github.io/CD_cwd_events/src/app/?settings%5Blabel%5D=Events+block&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_calendarurl%5D=%2F%2Fevents.cornell.edu%2Fapi%2F2.1%2Fevents&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_apikey%5D=KLhy2GtuSAGirYGY&settings%5Bcwd_events_display_config%5D%5Bcwd_events_format%5D=inline_compact&settings%5Bcwd_events_display_config%5D%5Bcwd_events_entries%5D=350&settings%5Bcwd_events_display_config%5D%5Bcwd_events_daysahead%5D=365&settings%5Bcwd_events_display_config%5D%5Bcwd_events_depts%5D=10848&settings%5Bcwd_events_display_config%5D%5Bcwd_events_group%5D=0&settings%5Bcwd_events_display_config%5D%5Bcwd_events_keyword%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_filterby%5D=none&settings%5Bcwd_events_display_options%5D%5Bcwd_events_truncatedescription%5D=150&settings%5Bcwd_events_display_options%5D%5Bcwd_events_hidedescription%5D=true&settings%5Bcwd_events_display_options%5D%5Bcwd_events_hideimages%5D=true&settings%5Bcwd_events_display_options%5D%5Bcwd_events_hideaddcal%5D=true&settings%5Bcwd_events_display_options%5D%5Bcwd_events_wrapperclass%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_listclass%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_itemclass%5D=)

**Comment by philwilliammee** [comment]
fixed in https://github.com/CU-CommunityApps/CD_cwd_events/releases/tag/v3.1.0
