### ISSUE TITLE
add setting for how many results per page

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events#12]
It would be super cool if there was a setting for how many results to show per page when your list is paginated.

(Not a critical priority of course, just an idea!)

**Comment by philwilliammee** [comment]
You can set results per page in the Number of Results field. [ This Demo ](https://cu-communityapps.github.io/CD_cwd_events/src/app/?settings%5Blabel%5D=Events+block&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_calendarurl%5D=%2F%2Fevents.cornell.edu%2Fapi%2F2.1%2Fevents&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_apikey%5D=KLhy2GtuSAGirYGY&settings%5Bcwd_events_display_config%5D%5Bcwd_events_format%5D=modern_compact&settings%5Bcwd_events_display_config%5D%5Bcwd_events_entries%5D=6&settings%5Bcwd_events_display_config%5D%5Bcwd_events_daysahead%5D=365&settings%5Bcwd_events_display_config%5D%5Bcwd_events_depts%5D=0&settings%5Bcwd_events_display_config%5D%5Bcwd_events_group%5D=0&settings%5Bcwd_events_display_config%5D%5Bcwd_events_keyword%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_filterby%5D=none&settings%5Bcwd_events_display_options%5D%5Bcwd_events_truncatedescription%5D=150&settings%5Bcwd_events_display_options%5D%5Bcwd_events_hidedescription%5D=true&settings%5Bcwd_events_display_options%5D%5Bcwd_events_hideaddcal%5D=true&settings%5Bcwd_events_display_options%5D%5Bcwd_events_wrapperclass%5D=cwd-card-grid+three-card&settings%5Bcwd_events_display_options%5D%5Bcwd_events_listclass%5D=cards&settings%5Bcwd_events_display_options%5D%5Bcwd_events_itemclass%5D=card) shows 6 results per page. To limit the number of pages reduce the number of days ahead.

**Comment by philwilliammee** [comment]
closed feature already exists
