### ISSUE TITLE
Query parms settings clarifications

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/CD_cwd_events#15]
Clarify in the widget wizard and/or the Drupal module (and WordPress plugin) settings which query param options are "AND" vs "OR" -- or maybe it's that, within each setting, it's "OR" (i.e. if you list multiple department IDs, it'll be "1234 or 5678 or 9876" -- same for groups and keywords?) but when multiple query params are used (i.e. if you provide a department ID and a keyword), it's "any of these dept ids AND any of these keywords"?

Also, does "keyword" allow multiple values like Groups and Departments?  (so, task 2: clarify keyword setting cardinality in the help text)

**Comment by philwilliammee** [comment]
I probably should add something in the readme about the localist api docs https://developer.localist.com/doc/api#usage 
usually for these things the best thing to do is just play around with the demo. [Click me for a example](https://cu-communityapps.github.io/CD_cwd_events/src/app/?settings%5Blabel%5D=Events+block&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_calendarurl%5D=https%3A%2F%2Fevents.cornell.edu%2Fapi%2F2.1%2Fevents&settings%5Bcwd_events_localist_config%5D%5Bcwd_events_apikey%5D=&settings%5Bcwd_events_display_config%5D%5Bcwd_events_format%5D=standard&settings%5Bcwd_events_display_config%5D%5Bcwd_events_entries%5D=3&settings%5Bcwd_events_display_config%5D%5Bcwd_events_daysahead%5D=365&settings%5Bcwd_events_display_config%5D%5Bcwd_events_depts%5D=4893%2C14006%2C4216&settings%5Bcwd_events_display_config%5D%5Bcwd_events_group%5D=5708&settings%5Bcwd_events_display_config%5D%5Bcwd_events_keyword%5D=teaching&settings%5Bcwd_events_display_options%5D%5Bcwd_events_filterby%5D=group&settings%5Bcwd_events_display_options%5D%5Bcwd_events_truncatedescription%5D=150&settings%5Bcwd_events_display_options%5D%5Bcwd_events_wrapperclass%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_listclass%5D=&settings%5Bcwd_events_display_options%5D%5Bcwd_events_itemclass%5D=)


The module builds a query that is made to to the localist api 

The localist api returns results with the three parameters Anded together:
- Departments are (OR)
- keywords (AND)
- Group_id (integer)

Currently the Drupal module does not support multiple keywords. The API does support multiple keywords but they would be ORed together and in most cases the resulting query is very small. If you have a project that requires multiple keywords put in a issue for it and I can add it.
